_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/deformable_optimizer_1x.yml',
  '_base_/deformable_detr_r50.yml',
  '_base_/deformable_detr_reader.yml',
]
weights: output/deformable_detr_r50_1x_coco/model_final
find_unused_parameters: True

pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_vb_normal_pretrained.pdparams

log_iter: 73
snapshot_epoch: 10
save_dir: output/obj2seq_decay/


BASE: obj2seq.yml


