architecture: OBJ2SEQ
#pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_vb_normal_pretrained.pdparams
pretrain_weights: ./output/obj2seq_r50_1x_coco/model_final.pdparams
hidden_dim: 256
#use_focal_loss: True


OBJ2SEQ:
  backbone: ResNet
  transformer: Obj_Transformer
  post_process: MutiClassPostProcess

ResNet:
  # index 0 stands for res2
  depth: 50
  norm_type: bn
  freeze_at: 0
  return_idx: [1, 2, 3]
  lr_mult_list: [0.0, 0.1, 0.1, 0.1]
  num_stages: 4


Obj_Transformer:
  num_queries: 100
  position_embed_type: sine
  nhead: 8
  num_encoder_layers: 6
  num_decoder_layers: 4
  dim_feedforward: 1024
  #dropout: 0.1
  dropout: 0.0
  activation: relu
  num_feature_levels: 4
  num_encoder_points: 4
  num_decoder_points: 4

MutiClassPostProcess: {}





